export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const SET_QUANTITY_TO_CART = "SET_QUANTITY_TO_CART"
export const ADD_PRODUCTS_TO_ORDER = "ADD_PRODUCTS_TO_ORDER"